#!/usr/bin/env node
/**
 * Generates one self-contained Docker build context per network:
 *
 *   deploy/torii-mainnet/     ← SN_MAIN
 *   deploy/torii-sepolia/     ← SN_SEPOLIA
 *
 * Each folder is template/ copied verbatim (Dockerfile, entrypoint.sh, scripts/) with
 * `ENV NETWORK=<net>` inserted into the Dockerfile, plus the root contracts.json.
 * Railway points a service's Root Directory at the folder — that is the whole setup.
 *
 * Usage:
 *   node scripts/build-deploy.mjs           regenerate deploy/
 *   node scripts/build-deploy.mjs --check   exit 1 if deploy/ is stale (run by `pnpm check`)
 */
import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const TEMPLATE = join(ROOT, 'template')
const check = process.argv.includes('--check')

// Everything in template/ except the Dockerfile ships verbatim; contracts.json comes from the root.
const SHIPPED = ['entrypoint.sh', 'scripts/generate-torii-config.mjs']

const contracts = JSON.parse(readFileSync(join(ROOT, 'contracts.json'), 'utf8'))
const template = readFileSync(join(TEMPLATE, 'Dockerfile'), 'utf8')

const ENV_ANCHOR = 'ENV TORII_DB_DIR='
if (!template.includes(ENV_ANCHOR)) die(`template/Dockerfile: cannot find "${ENV_ANCHOR}" to insert NETWORK before`)
// The torii release is pinned per network in contracts.json and stamped into these two ARGs.
const TORII_ARGS = ['TORII_REPO', 'TORII_TAG']
for (const a of TORII_ARGS) if (!template.includes(`\nARG ${a}\n`)) die(`template/Dockerfile: cannot find a bare "ARG ${a}" line to fill in`)

function die(msg) {
  console.error(`ERROR: ${msg}`)
  process.exit(1)
}

/** SN_MAIN → mainnet, SN_SEPOLIA → sepolia */
function slugOf(network) {
  const m = /^SN_([A-Z0-9]+)$/.exec(network)
  if (!m) die(`network "${network}": expected SN_<NAME>`)
  return m[1].toLowerCase() === 'main' ? 'mainnet' : m[1].toLowerCase()
}

function renderDockerfile(network, slug) {
  const torii = contracts[network].torii
  const header = [
    `# GENERATED by scripts/build-deploy.mjs from template/Dockerfile — do not edit.`,
    `# Network: ${network}. Torii: ${torii.repo} ${torii.tag}. Railway: Root Directory = deploy/torii-${slug}. Regenerate: pnpm build`,
    ``,
  ].join('\n')
  return header + template
    .replace('\nARG TORII_REPO\n', `\nARG TORII_REPO=${torii.repo}\n`)
    .replace('\nARG TORII_TAG\n', `\nARG TORII_TAG=${torii.tag}\n`)
    .replace(ENV_ANCHOR, `ENV NETWORK=${network}\n${ENV_ANCHOR}`)
}

function renderReadme(network, slug) {
  return `# torii-${slug} — ${network}

GENERATED by \`pnpm build\` — do not edit. Railway builds this folder as-is.

Railway service settings: Root Directory \`deploy/torii-${slug}\`, Volume at \`/data\`, a domain
on the app port. Nothing else — the network is baked into the Dockerfile.
`
}

function renderFiles(network) {
  const slug = slugOf(network)
  const files = new Map([
    ['Dockerfile', renderDockerfile(network, slug)],
    ['README.md', renderReadme(network, slug)],
  ])
  for (const rel of SHIPPED) files.set(rel, readFileSync(join(TEMPLATE, rel), 'utf8'))
  files.set('contracts.json', readFileSync(join(ROOT, 'contracts.json'), 'utf8'))
  return { slug, files }
}

// Prove the config actually generates for every network before writing anything.
for (const network of Object.keys(contracts)) {
  try {
    execFileSync('node', [join(TEMPLATE, 'scripts/generate-torii-config.mjs'), '--print', '-n', network, '-c', join(ROOT, 'contracts.json')], { stdio: 'pipe' })
  } catch (e) {
    die(`${network}: config generation fails\n${e.stderr}`)
  }
}

let stale = []
for (const network of Object.keys(contracts)) {
  const { slug, files } = renderFiles(network)
  const dir = join(ROOT, 'deploy', `torii-${slug}`)

  if (check) {
    for (const [rel, want] of files) {
      const path = join(dir, rel)
      if (!existsSync(path) || readFileSync(path, 'utf8') !== want) stale.push(`deploy/torii-${slug}/${rel}`)
    }
    // anything extra in the folder is also drift
    const walk = (d, prefix = '') => readdirSync(d, { withFileTypes: true }).flatMap((e) =>
      e.isDirectory() ? walk(join(d, e.name), `${prefix}${e.name}/`) : [`${prefix}${e.name}`])
    if (existsSync(dir)) for (const rel of walk(dir)) if (!files.has(rel)) stale.push(`deploy/torii-${slug}/${rel} (unexpected)`)
    continue
  }

  rmSync(dir, { recursive: true, force: true })
  for (const [rel, content] of files) {
    mkdirSync(dirname(join(dir, rel)), { recursive: true })
    writeFileSync(join(dir, rel), content, { mode: rel.endsWith('.sh') ? 0o755 : 0o644 })
  }
  console.log(`deploy/torii-${slug}/  ← ${network}  (${files.size} files)`)
}

if (check) {
  if (stale.length) die(`deploy/ is stale — run \`pnpm build\` and commit:\n  ${stale.join('\n  ')}`)
  console.log('deploy/ is up to date')
}
